### ISSUE TITLE
Tests failing on Chrome OS X 40.0.2214.94 (64-bit)

### ISSUE THREAD

**Issue by fabb** [facebook/css-layout#29]
```
101 specs, 3 failures, 5 pending specs
Spec List | Failures
Layout should layout text with flexDirection row
Expected {name: 'expected-dom', width: 200, height: 58, top: 0, left: 0, children: [{width: 200, height: 58, top: 0, left: 0, children: [{width: 172.421875, height: 16, top: 20, left: 20}]}]} 
to equal {name: 'expected-dom', width: 200, height: 56, top: 0, left: 0, children: [{width: 200, height: 56, top: 0, left: 0, children: [{width: 172.421875, height: 16, top: 20, left: 20}]}]}.
Error: Expected {name: 'expected-dom', width: 200, height: 58, top: 0, left: 0, children: [{width: 200, height: 58, top: 0, left: 0, children: [{width: 172.421875, height: 16, top: 20, left: 20}]}]} 
to equal {name: 'expected-dom', width: 200, height: 56, top: 0, left: 0, children: [{width: 200, height: 56, top: 0, left: 0, children: [{width: 172.421875, height: 16, top: 20, left: 20}]}]}.
    at stack (https://jasmine.github.io/2.0/lib/jasmine.js:1293:17)
    at buildExpectationResult (https://jasmine.github.io/2.0/lib/jasmine.js:1270:14)
    at Spec.Env.expectationResultFactory (https://jasmine.github.io/2.0/lib/jasmine.js:484:18)
    at Spec.addExpectationResult (https://jasmine.github.io/2.0/lib/jasmine.js:260:46)
    at Expectation.addExpectationResult (https://jasmine.github.io/2.0/lib/jasmine.js:442:21)
    at Expectation.toEqual (https://jasmine.github.io/2.0/lib/jasmine.js:1209:12)
    at testNamedLayout (file:///Users/fabian/dev/css-layout/src/Layout-test-utils.js:248:8)
    at layoutTestUtils.testLayout (file:///Users/fabian/dev/css-layout/src/Layout-test-utils.js:387:7)
    at Object.<anonymous> (file:///Users/fabian/dev/css-layout/src/__tests__/Layout-test.js:895:56)
    at attemptSync (https://jasmine.github.io/2.0/lib/jasmine.js:1510:12)
Layout should layout with text and margin
Expected {name: 'expected-dom', width: 200, height: 76, top: 0, left: 0, children: [{width: 200, height: 76, top: 0, left: 0, children: [{width: 160, height: 32, top: 20, left: 20}]}]} 
to equal {name: 'expected-dom', width: 200, height: 72, top: 0, left: 0, children: [{width: 200, height: 72, top: 0, left: 0, children: [{width: 160, height: 32, top: 20, left: 20}]}]}.
Error: Expected {name: 'expected-dom', width: 200, height: 76, top: 0, left: 0, children: [{width: 200, height: 76, top: 0, left: 0, children: [{width: 160, height: 32, top: 20, left: 20}]}]} 
to equal {name: 'expected-dom', width: 200, height: 72, top: 0, left: 0, children: [{width: 200, height: 72, top: 0, left: 0, children: [{width: 160, height: 32, top: 20, left: 20}]}]}.
    at stack (https://jasmine.github.io/2.0/lib/jasmine.js:1293:17)
    at buildExpectationResult (https://jasmine.github.io/2.0/lib/jasmine.js:1270:14)
    at Spec.Env.expectationResultFactory (https://jasmine.github.io/2.0/lib/jasmine.js:484:18)
    at Spec.addExpectationResult (https://jasmine.github.io/2.0/lib/jasmine.js:260:46)
    at Expectation.addExpectationResult (https://jasmine.github.io/2.0/lib/jasmine.js:442:21)
    at Expectation.toEqual (https://jasmine.github.io/2.0/lib/jasmine.js:1209:12)
    at testNamedLayout (file:///Users/fabian/dev/css-layout/src/Layout-test-utils.js:248:8)
    at layoutTestUtils.testLayout (file:///Users/fabian/dev/css-layout/src/Layout-test-utils.js:387:7)
    at Object.<anonymous> (file:///Users/fabian/dev/css-layout/src/__tests__/Layout-test.js:910:41)
    at attemptSync (https://jasmine.github.io/2.0/lib/jasmine.js:1510:12)
Layout tests consts keeps browser text measurements in sync with predefined consts
Expected {smallWidth: 34.671875, smallHeight: 18, bigWidth: 172.421875, bigHeight: 36, bigMinWidth: 100.453125} 
to equal {smallWidth: 34.671875, smallHeight: 16, bigWidth: 172.421875, bigHeight: 32, bigMinWidth: 100.453125}, 'Looks like browser has updated its text measurements functions. You need to update `preDefinedTextSizes` in Layout-test-utils.js'.
Error: Expected {smallWidth: 34.671875, smallHeight: 18, bigWidth: 172.421875, bigHeight: 36, bigMinWidth: 100.453125} 
to equal {smallWidth: 34.671875, smallHeight: 16, bigWidth: 172.421875, bigHeight: 32, bigMinWidth: 100.453125}, 'Looks like browser has updated its text measurements functions. You need to update `preDefinedTextSizes` in Layout-test-utils.js'.
    at stack (https://jasmine.github.io/2.0/lib/jasmine.js:1293:17)
    at buildExpectationResult (https://jasmine.github.io/2.0/lib/jasmine.js:1270:14)
    at Spec.Env.expectationResultFactory (https://jasmine.github.io/2.0/lib/jasmine.js:484:18)
    at Spec.addExpectationResult (https://jasmine.github.io/2.0/lib/jasmine.js:260:46)
    at Expectation.addExpectationResult (https://jasmine.github.io/2.0/lib/jasmine.js:442:21)
    at Expectation.toEqual (https://jasmine.github.io/2.0/lib/jasmine.js:1209:12)
    at Object.<anonymous> (file:///Users/fabian/dev/css-layout/src/__tests__/Layout-consts-test.js:16:33)
    at attemptSync (https://jasmine.github.io/2.0/lib/jasmine.js:1510:12)
    at QueueRunner.run (https://jasmine.github.io/2.0/lib/jasmine.js:1498:9)
    at QueueRunner.execute (https://jasmine.github.io/2.0/lib/jasmine.js:1485:10)
    at Spec.Env.queueRunnerFactory (https://jasmine.github.io/2.0/lib/jasmine.js:518:35)
```

**Comment by vjeux** [comment]
Grrr

```
Expected {smallWidth: 34.671875, smallHeight: 18, bigWidth: 172.421875, bigHeight: 36, bigMinWidth: 100.453125} 
to equal {smallWidth: 34.671875, smallHeight: 16, bigWidth: 172.421875, bigHeight: 32, bigMinWidth: 100.453125}, 'Looks like browser has updated its text measurements functions. You need to update `preDefinedTextSizes` in Layout-test-utils.js'.
```

looks like smallHeight and bigHeight changed from 18 to 16 and 36 to 32. Can you make sure you aren't zoomed by chance?

**Comment by fabb** [comment]
Zoom is at 100%. If I zoom in or out, a lot more tests fail.
I have a retina display, might that be related?

**Comment by jimmyhmiller** [comment]
I am getting the exact same errors. I've tried on both a retina and non-retina display. Assuming that the error message given is correct. It looks like chrome has changed their text measurements functions and if you look at the other two tests that are failing, they appear to be off by exactly that amount. 

I've put in a pull request for this https://github.com/facebook/css-layout/pull/35.

**Comment by vjeux** [comment]
@jimmyhmiller thanks, it fixed it :)
